source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'YPublicModuleDemo' do
    pod 'Alamofire'	# 网络
    pod 'Kingfisher'  	# 图片异步加载
    pod 'SnapKit'    	# 代码约束
    pod 'Toast-Swift'
end
